name: common-ci-cd
on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      component:
        required: true
        type: string
      app-type:
        required: true
        type: string

jobs:
  ci:
    runs-on: self-hosted
    outputs:
      app_version: ${{ steps.package-version.outputs.version }}
    steps:
    - name: checkout
      uses : actions/checkout@v5

    - name: display the files
      run : ls -la

    - name:  print inputs
      run : echo "Project ${{ inputs.project }}"

    - name: Get app version
      id: package-version
      run: echo "version=$(jq -r '.version' package.json)" >> "$GITHUB_OUTPUT"
    
    - name:  print app version
      run : echo ${{ steps.package-version.outputs.version }}