name: common-ci-cd
on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      component:
        required: true
        type: string
      app-type:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY: 
        required: true
jobs:
  ci:
    runs-on: self-hosted
    outputs:
      appVersion: ${{ steps.package-version.outputs.version }}
    steps:
    - name: checkout
      uses : actions/checkout@v5

    - name: display the files
      run : ls -la

    - name:  print inputs
      run : echo "Project ${{ inputs.project }}"

    - name: Get app version
      id: package-version
      run: echo "version=$(jq -r '.version' package.json)" >> "$GITHUB_OUTPUT"
    
    - name:  print app version
      run : echo ${{ steps.package-version.outputs.version }}

    - name: install dependencies
      run:  npm install

    - name: docker build
      run: docker build -t 989088456804.dkr.ecr.us-east-1.amazonaws.com/roboshop/${{ inputs.component }}:${{ steps.package-version.outputs.version }} .

    - name: Configure AWS Credentials 
      uses: aws-actions/configure-aws-credentials@v5.0.0
      with:
        aws-region: us-east-1
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: push the image to ecr
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 989088456804.dkr.ecr.us-east-1.amazonaws.com


        docker push 989088456804.dkr.ecr.us-east-1.amazonaws.com/roboshop/catalogue:${{ steps.package-version.outputs.version }}





  cd:
    runs-on: self-hosted
    needs: ci
    env:
      appVersion: ${{ needs.ci.outputs.appVersion }}
    steps:
      - name: checkout deploy repo
        uses: actions/checkout@v6
        with:
          repository: raheemdevops-actions/catalogue-deploy
      - name: check files
        run: ls -l
          
